name: Brandon Chase Music
favicon: null
layout_spectrum: 0.295
typography_spectrum: 0.49766048276796937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26211b'
    - '#e3eaf4'
    - '#7b8428'
    - '#90a43f'
    - '#546563'
  brandStrength: 0.625
  lightness: 0.8388792837504297
  saturation: 0.8075615856796503
  rhythmicContrast: 0.707463615341112
purpose: []
