name: Brandon Chase Music
favicon: null
layout_spectrum: 0.3987032182049006
typography_spectrum: 0.49766048276796937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6723020242061466
  lightness: 0.8388792837504297
  saturation: 0.8075615856796503
  rhythmicContrast: 0.707463615341112
purpose: []
